### ISSUE TITLE
Класс страницы не обрабатывается

### ISSUE THREAD

**Issue by Sulpher** [AlekVolsk/Blank-page#2]
В настройках пункта меню есть класс страницы. В некоторых ситуациях он нужен. 
Сейчас не обрабатывается.

**Comment by AlekVolsk** [comment]
Класс страницы вешается на `<body>`, это должно обрабатываться шаблоном, от компонента это не зависит.

**Comment by Sulpher** [comment]
перед тем, как запостить этот issue, я проверил на master3lite и protostar - в обоих случаях класс не добавлялся. а вот для пункта меню блог категории добавлялся. поэтому подумал, что проблема в компоненте.
