### ISSUE TITLE
Problem with metadescription again!

### ISSUE THREAD

**Issue by Strngest** [AlekVolsk/Blank-page#3]
Hello, Alek! BlankPage is a Supercomponent, thanks a lot! But in version 1.0.4 again there was a problem with metadescription of blank page, although in version 1.0.3 this problem was solved. Now the metadescription of the main page of the site is displayed instead of the current one. I hope for your help.

For information:
PHP version 7.4.29
Joomla! 3.10.8

**Comment by AlekVolsk** [comment]
fixed on v1.0.5
